/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonCard: typeof import('./src/components/CommonCard.vue')['default']
    ContentItem: typeof import('./src/components/creator/ContentItem.vue')['default']
    Dropdown: typeof import('./src/components/ui/Dropdown.vue')['default']
    NoteItem: typeof import('./src/components/NoteItem.vue')['default']
    NoteList: typeof import('./src/components/NoteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
